language: objective-c
osx_image: xcode8

# iOS tests just timeout on Travis, hopefully will fix by full release
#  - DESTINATION='platform=iOS Simulator,name=iPhone 6S' ACTION=test

env:
  - "DESTINATION='platform=OS X' ACTION=test"
  - "DESTINATION='platform=watchOS Simulator,name=Apple Watch - 38mm' ACTION=build"
  - "DESTINATION='platform=tvOS Simulator,name=Apple TV 1080p' ACTION=test"

script:
  - set -o pipefail && xcodebuild -scheme PromiseKit -destination "$DESTINATION" $ACTION | xcpretty

after_success:
  - bash <(curl -s https://codecov.io/bash)
